Event enhancements
SK-Brno-Zabovresky/bzl_web pull request #32
Opened 2022-12-06 22:15 UTC by jakub-h

Better date presenting
Marking already happened events
Show which events are counted to BZL

2022-12-06 22:17 UTC, jakub-h commented
fixes #26 
fixes #25

2022-12-08 08:51 UTC, otahirs requested changes

2022-12-08 08:51 UTC, otahirs commented on app.py
> +    locale.setlocale(locale.LC_ALL, "cs_CZ")
locale neni potreba. u `%d. %m. %Y` bude vzdy stejny output

2022-12-08 13:02 UTC, jakub-h commented on app.py
> +    locale.setlocale(locale.LC_ALL, "cs_CZ")
opraveno v 3c5f6de

2022-12-08 13:04 UTC, otahirs approved these changes

2022-12-08 13:37 UTC, merged

2022-12-09 12:48 UTC, otahirs commented
@jakub-h Nenastavime spíš celému divu probehleho eventu třeba `opacity: 0.6`. 🤔 Takto je něco zasedle a něco ne.

2022-12-09 13:25 UTC, jakub-h commented
> @jakub-h Nenastavime spíš celému divu probehleho eventu třeba `opacity: 0.6`. thinking Takto je něco zasedle a něco ne.

Uplne klidne. Jak rikam, ja ve frontendu nejsem vubec kovanej. Udelal jsem prvni vec, co me napadla. Klidne si s tim pohraj a najdi lepsi a hezci variantu :slightly_smiling_face: