Fix year generator
SK-Brno-Zabovresky/bzl_web pull request #34
Opened 2022-12-08 15:11 UTC by saytaM12

closes #21

Smazal jsem javascript na generování ročníků a přesunul to do pythonu.
Taky se bude měnit ročník v půlce roku a ne na začátku

2022-12-09 09:00 UTC, jakub-h commented
Prvni dulezita vec, kdyz delas novou feature a chces ji pote mergnout do mastera, tak spravny postup je nasledujici (predpokladam, ze mas ciste repo, vsechno je commitle a nemas zadne zmenene soubory):
- `git checkout master`
- `git pull`
- `git checkout -b <nazev-tve-branche>`
- add, commit, push (klidne vickrat, zejo)
- za predpokladu, ze se master mezi tim nezmenil, muzes jit do GitHubu a vytvorit PR

problem nastava ve chvili, kdy se master mezi tim zmenil. Pak musis pred vytvorenim PR jeste udelat rebase nad aktualniho mastera:
- `git checkout master`
- `git pull`
- `git checkout <nazev-tve-branche>`
- `git rebase -i master`
- vyresit konflikty, dokoncit rebase
- `git push -f`

Tim se dostavame k tvemu aktualnimu problemu. Chces mergovat do masteru svou vetev, ktera ale vychazi z o moc starsi verze (a dokonce ani ne z mastera). Je to pekne videt v grafu (at uz tady, nebo ve vscode). Spravny stav je takovy, ze tva nova branch linearne vychazi z aktualniho mastera, do ktereho chces mergovat.

Rebasni se prosim tedy nad aktualni stav mastera, at tam nejsou ty konflikty. Jestli chces, muzeme si k tomu vecer sednout spolu.

2022-12-09 12:38 UTC, otahirs requested changes
stáhni si aktuální master:  
kdybys neměl nic commitle tak můžeš udělat 
```bash
git stash # ulozis a schovas změny abys mohl pullout 
git pull origin master 
git stash pop # vrátíš změny
# upravíš případné soubory s konflikty 
```
takto chceš přidat svoje změny na konec masteru, abys je pak mohl mergnout 
```bash
git rebase master 
```
pokud v tom máš větší bordel, tak ti někdo z nás pomůže

2022-12-09 12:38 UTC, otahirs commented on app.py
> +    zakYear = date.today().year - (14 - math.floor(date.today().month / 6))
navrhuji 
```py
zakYear = date.today().year - 14 + (date.today().month > 6)
```
nebo
```py
zakYear = date.today().year - 14 + (date.today().month % 10)

```

2022-12-09 13:28 UTC, jakub-h commented on app.py
> +    zakYear = date.today().year - (14 - math.floor(date.today().month / 6))
V ramci pythonu tu pouzivame snake_case, tak bych se toho prosim drzel.

2022-12-09 23:05 UTC, otahirs approved these changes

2022-12-11 19:20 UTC, jakub-h commented
Osobne jsem teda v podobnych pripadech vetsi fanda rebasu nad mastera, nez primergovani mastera. Je z toho imho lip videt, co presne menily tve commity. Ale to je asi jen otazka osobniho vkusu. Vypada to, ze to je vpohode.

2022-12-11 19:22 UTC, jakub-h commented on app.py
> +    return render_template("home.html", zakYear=zak_year, vetYear=vet_year)
zachoval bych snake_case i pro jmena atributu. A taky bych asi zkusil udrzet ve jmenech promennych jen anglictinu.
Navrhuju napr.: `kid_year` a `vet_year`

2022-12-11 19:26 UTC, jakub-h commented
Krom te jedne drobnosti uz mi to prijde gut a chtel bych dat approve. Nemuzu ho tady ale nikde najit :smile:

2022-12-11 19:27 UTC, otahirs commented
> Krom te jedne drobnosti uz mi to prijde gut a chtel bych dat approve. Nemuzu ho tady ale nikde najit smile

File changes -> add review

2022-12-11 19:44 UTC, jakub-h approved these changes

2022-12-14 11:41 UTC, merged