Basic single-event and calendar pages
SK-Brno-Zabovresky/bzl_web pull request #8
Opened 2022-11-13 15:06 UTC by jakub-h

Closes #6 

Podporuje jak zavody v orisu, tak mimo oris. Zobrazeni je zatim opravdu zakladni.

2022-11-13 15:43 UTC, otahirs requested changes

2022-11-13 15:43 UTC, otahirs commented on src/event.py
> +    def get_info_from_oris(oris_id: int) -> Dict:
davalo by me vetsi smysl mit vetsi encapsulaci vnitrnich dat a mit neco jako  
`Event.append_oris_data(oris_id: int) -> Event`

2022-11-13 15:43 UTC, otahirs commented on src/event.py
> +    def get_all_events(cls, season: str, as_dicts: bool = False) -> Dict:
cekal bych ze `Event` classa bude mit pouze metody manipulujici se sebou.   
methodu `get_all_events() -> Event[]` bych celal na necem jako `EventRepo`

2022-11-14 19:48 UTC, jakub-h commented on src/event.py
> +    def get_info_from_oris(oris_id: int) -> Dict:
Muze byt treba takto?
[a5d05ee](https://github.com/SK-Brno-Zabovresky/bzl_web/pull/8/commits/a5d05ee860690604b2cdc4c1825dd9289c953b7f)

2022-11-14 19:48 UTC, jakub-h commented on src/event.py
> +    def get_all_events(cls, season: str, as_dicts: bool = False) -> Dict:
Muze byt treba takto?
[a5d05ee](https://github.com/SK-Brno-Zabovresky/bzl_web/pull/8/commits/a5d05ee860690604b2cdc4c1825dd9289c953b7f)

2022-11-14 20:00 UTC, otahirs approved these changes

2022-11-14 20:01 UTC, saytaM12 approved these changes
píše mi to, že mám dát svoje review. mě se to líbí :)

(četl jsem si to a asi tam fakt nenajdu něco co bych změnil)

2022-11-15 06:53 UTC, jakub-h commented
> něco



> píše mi to, že mám dát svoje review. mě se to líbí :)
> 
> (četl jsem si to a asi tam fakt nenajdu něco co bych změnil, tolik zkušeností nemám)

Úplně v pohodě. Je dobré se na PR dívat, i když se zatím necítíš na navrhování úprav. Pochopíš tím, jak daná část funguje (obzvlášť užitečné v takto malém projektu) a třeba se i něco přiučíš. 
Když tam ale uvidíš něco, co ti nedává smysl, šlo by to napsat líp, nebo bys to jen chtěl vysvětlit, rozhodně se neostýchej napsat.

2022-11-15 06:53 UTC, merged